
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import {DataProvider} from "./provider/DataProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Inventify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DataProvider>
           {/* main layout  */}
        <section className="flex justify-between w-full">
                {/* sidebar  */}
       <div className="fixed md:w-1/4 h-screen ">
       <Sidebar/>
       </div>
       <div className="w-3/4 ml-[25%]">
                {/* Navbar  */}
       <Navbar/>
            {/*main dynamic routes section*/}
      <main className="bg-gray-100 w-full h-full min-h-screen">
      {children}
      </main>
       </div>
       </section>
        </DataProvider>
            
      
      </body>
    </html>
  );
}
